CC = g++
CFLAGS = -std=c++17
CXXFLAGS = -std=c++17
default:Calculator

Calculator : Calculator.o largeint.o

Calculator.o : calculator.cpp bigintdivresult.h	 setting.h stack.hpp unsortedlist.hpp Pool.hpp

largeint.o: largeint.cpp largeint.h Pool.hpp unsortedlist.hpp


